// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zonmgrikdlluurysjcno.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpvbm1ncmlrZGxsdXVyeXNqY25vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcyMzA0NjcsImV4cCI6MjA3MjgwNjQ2N30.2eZ3jkZiHWBprja4reLLElzSgNMeY-1NivatkIOeb1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});